mod support;

use std::{fs, process::Command};

use signal_domain::bootstrap_manifest as manifest;
use slice_core_ethos::bootstrap::{
    BootstrapBody, Declaration, ShapeApplication, TypeBody, TypeExpression, VariantBody,
};
use slice_core_logos::{
    WholeLogos, WholeLogosItem, WholeLogosTypeReference, WholeLogosVariantPayload,
};
use slice_core_nomos::BootstrapSliceOneLowering;
use slice_rust_logos::RustEncodedIdCodec;

use support::{DomainRustTypePaths, SIGNAL_DOMAIN_REVISION, SOURCE};

const CARGO_MANIFEST: &str = include_str!("../Cargo.toml");
const FLAKE: &str = include_str!("../flake.nix");
const GENERATED_MARKER: &str =
    "// @generated by schema-rust from an authority-verified bootstrap Interface\n\n";

fn type_declaration<'a>(
    body: &'a slice_core_ethos::bootstrap::InterfaceBody,
    spelling: &str,
) -> &'a slice_core_ethos::bootstrap::TypeDeclaration {
    let identity = support::declaration(spelling);
    body.types
        .iter()
        .find_map(|declaration| match declaration {
            Declaration::Type(declaration) if declaration.name == identity => Some(declaration),
            _ => None,
        })
        .unwrap_or_else(|| panic!("missing authority-seated declaration {spelling}"))
}

fn assert_application(
    declaration: &slice_core_ethos::bootstrap::TypeDeclaration,
    expected_shape_local: u16,
    expected_argument: &str,
) {
    let TypeBody::Newtype(TypeExpression::ShapeApplication(ShapeApplication { shape, arguments })) =
        &declaration.body
    else {
        panic!("expected a Shape-backed newtype")
    };
    assert_eq!(shape, &support::universal(expected_shape_local));
    assert_eq!(
        arguments,
        &[TypeExpression::Reference(support::declaration(
            expected_argument
        ))]
    );
}

fn executable_enumerations(logos: &WholeLogos) -> WholeLogos {
    WholeLogos::new(
        logos
            .items()
            .iter()
            .filter(|item| matches!(item, WholeLogosItem::Enumeration(_)))
            .cloned()
            .collect(),
    )
}

fn emitted_name(identity: &slice_signal_sema_translator::VocabularyEncodedId) -> String {
    RustEncodedIdCodec::encode(identity)
}

fn construct_enumeration_value(
    logos: &WholeLogos,
    identity: &slice_signal_sema_translator::VocabularyEncodedId,
) -> String {
    let enumeration = logos
        .items()
        .iter()
        .find_map(|item| match item {
            WholeLogosItem::Enumeration(candidate) if candidate.name() == identity => {
                Some(candidate)
            }
            _ => None,
        })
        .expect("payload target enumeration is present");
    let variant = enumeration
        .variants()
        .iter()
        .find(|candidate| candidate.payload() == &WholeLogosVariantPayload::Unit)
        .unwrap_or_else(|| &enumeration.variants()[0]);
    let prefix = format!(
        "{}::{}",
        emitted_name(identity),
        emitted_name(variant.name())
    );
    match variant.payload() {
        WholeLogosVariantPayload::Unit => prefix,
        WholeLogosVariantPayload::Tuple(fields) => {
            let [WholeLogosTypeReference::Identity(payload)] = fields.fields() else {
                panic!("Spirit payload variants each carry one identity")
            };
            format!("{prefix}({})", construct_enumeration_value(logos, payload))
        }
    }
}

fn behavior_source(emitted: &str, logos: &WholeLogos) -> String {
    let mut source = String::from(emitted);
    source.push_str("\nfn main() {\n");
    let mut exercised = 0;
    for item in logos.items() {
        let WholeLogosItem::Enumeration(enumeration) = item else {
            continue;
        };
        let enumeration_name = emitted_name(enumeration.name());
        for variant in enumeration.variants() {
            let variant_name = emitted_name(variant.name());
            match variant.payload() {
                WholeLogosVariantPayload::Unit => source.push_str(
                    format!("    let _ = {enumeration_name}::{variant_name};\n").as_str(),
                ),
                WholeLogosVariantPayload::Tuple(fields) => {
                    let [WholeLogosTypeReference::Identity(payload)] = fields.fields() else {
                        panic!("Spirit payload variants each carry one identity")
                    };
                    source.push_str(
                        format!(
                            "    let _ = {enumeration_name}::{variant_name}({});\n",
                            construct_enumeration_value(logos, payload),
                        )
                        .as_str(),
                    );
                }
            }
            exercised += 1;
        }
    }
    source.push_str(format!("    println!(\"{exercised}\");\n}}\n").as_str());
    source
}

#[test]
fn complete_spirit_domain_is_one_verified_transaction_through_rust() {
    let assembly = support::assembly();
    assert_eq!(assembly.canonical_source(), SOURCE);
    assert_eq!(
        assembly.canonical_source(),
        signal_domain::DOMAIN_INTERFACE_SOURCE
    );

    let BootstrapBody::Interface(body) = &assembly.transaction().decoded().document.body else {
        panic!("Spirit-domain must remain an Interface")
    };
    assert!(body.inputs.is_empty());
    assert!(body.outputs.is_empty());
    assert!(body.refusals.is_empty());
    assert!(body.memberships.is_empty());
    assert_eq!(body.types.len(), 41);

    let expected_top_level = manifest::DECLARATION_SEATS
        .iter()
        .filter(|seat| seat.owner_local.is_none())
        .map(|seat| support::universal(seat.local))
        .collect::<Vec<_>>();
    let actual_top_level = body
        .types
        .iter()
        .map(|declaration| match declaration {
            Declaration::Type(declaration) => declaration.name.clone(),
            Declaration::Nomos(_) => panic!("taxonomy contains only type declarations"),
        })
        .collect::<Vec<_>>();
    assert_eq!(actual_top_level, expected_top_level);

    let mut enumerations = 0;
    let mut newtypes = 0;
    let mut variants = 0;
    let mut payload_variants = 0;
    for declaration in &body.types {
        let Declaration::Type(declaration) = declaration else {
            panic!("taxonomy contains only type declarations")
        };
        match &declaration.body {
            TypeBody::Enum(declared_variants) => {
                enumerations += 1;
                variants += declared_variants.len();
                payload_variants += declared_variants
                    .iter()
                    .filter(|variant| !matches!(variant.body, VariantBody::Unit))
                    .count();
            }
            TypeBody::Newtype(_) => newtypes += 1,
            TypeBody::Struct(_) => panic!("Spirit taxonomy has no product declarations"),
        }
    }
    assert_eq!(
        (enumerations, newtypes, variants, payload_variants),
        (38, 3, 369, 37)
    );

    assert_application(
        type_declaration(body, "DomainScope"),
        manifest::SCOPEOF_SEAT.local,
        "Domain",
    );
    for spelling in ["DomainScopes", "ScopeSet"] {
        assert_application(
            type_declaration(body, spelling),
            manifest::VECTOR_SEAT.local,
            "DomainScope",
        );
    }

    let logos = BootstrapSliceOneLowering::new()
        .lower(assembly.reader(), assembly.transaction())
        .expect("Nomos revalidates and lowers the sealed Spirit transaction");
    assert_eq!(logos.items().len(), 41);
    let identity = logos
        .content_identity()
        .expect("complete Spirit Logos has whole-content identity");
    let archived = logos
        .to_archive_bytes()
        .expect("archive complete Spirit Logos");
    let restored =
        WholeLogos::from_archive_bytes(&archived).expect("restore complete Spirit Logos");
    assert_eq!(restored, logos);
    assert_eq!(
        restored.content_identity().expect("restored identity"),
        identity
    );

    let rust = support::rust_logos();
    let projected = rust
        .emit_with_type_paths(&restored, assembly.resolver(), &DomainRustTypePaths::new())
        .expect("Rust Logos projects the exact sealed transaction");
    assert_eq!(
        format!("{GENERATED_MARKER}{projected}"),
        signal_domain::DOMAIN_INTERFACE_RUST,
        "the witness and producer must project byte-identical Rust"
    );
    for source_spelling in ["Domain", "DomainScope", "ScopeOf"] {
        assert!(!projected.contains(source_spelling));
    }

    let executable = executable_enumerations(&restored);
    let executable_rust = rust
        .emit_with_type_paths(
            &executable,
            assembly.resolver(),
            &DomainRustTypePaths::new(),
        )
        .expect("Rust Logos emits every Spirit enumeration");
    let temporary = tempfile::tempdir().expect("scratch crate directory");
    fs::create_dir(temporary.path().join("src")).expect("scratch source directory");
    fs::write(
        temporary.path().join("Cargo.toml"),
        "[package]\nname=\"spirit-domain-generated\"\nversion=\"0.0.0\"\nedition=\"2024\"\n",
    )
    .expect("scratch manifest");
    fs::write(
        temporary.path().join("src/main.rs"),
        behavior_source(&executable_rust, &executable),
    )
    .expect("scratch generated source and behavior harness");
    let run = Command::new("cargo")
        .args([
            "run",
            "--quiet",
            "--offline",
            "--manifest-path",
            temporary
                .path()
                .join("Cargo.toml")
                .to_str()
                .expect("UTF-8 scratch path"),
        ])
        .env("CARGO_TARGET_DIR", temporary.path().join("target"))
        .output()
        .expect("run scratch Cargo build");
    assert!(
        run.status.success(),
        "scratch Cargo stderr:\n{}",
        String::from_utf8_lossy(&run.stderr)
    );
    assert_eq!(
        String::from_utf8(run.stdout).expect("scratch output is UTF-8"),
        "369\n"
    );
}

#[test]
fn fixture_and_runtime_type_share_the_exact_published_source() {
    assert!(FLAKE.contains(SIGNAL_DOMAIN_REVISION));
    assert!(!CARGO_MANIFEST.contains("schema-rust"));
    assert!(CARGO_MANIFEST.contains("signal-domain"));
    assert!(CARGO_MANIFEST.contains(SIGNAL_DOMAIN_REVISION));
}
